# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: flightTracker # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  profile: pipe
  memorySize: 128
# you can overwrite defaults here
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:us-east-1:586011406659:table/"
            - "Ref" : "FlightsTrackerTable"
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource:
        Fn::GetAtt: 
          - FlightsTrackerTable
          - StreamArn

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  trackFlights:
    handler: getPrices.handle
    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
     - schedule: rate(23 hours)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000

  checkPrices:
    handler: checkPrices.handle
    events:
     - stream: 
       arn:
         Fn::GetAtt: 
           - FlightsTrackerTable
           - StreamArn

# you can add CloudFormation resource templates here
resources:
 Resources:
   FlightsTrackerTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: FlightsPriceTracker
       AttributeDefinitions:
         - AttributeName: timestamp
           AttributeType: S
       KeySchema:
         - AttributeName: timestamp
           KeyType: HASH
       ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
       StreamSpecification:
         StreamViewType: NEW_IMAGE
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
